id: P4360F0F6
initial_creation_type: input
source_metadata:
  title: Sang Offering
  language: de
  description: 'Texts on the subject of Sang (bsang/bsangs) or Purificatory Incense
    Smoke Offering:'
  volume:
    36c18a9ffb624fa79f66e385ec30ff48:
      title: A Guide to the Practice of Sang
      parent: Commentaries
    71b98533714b42f58be46ff4cd9768f5:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    741e2218debb4e4d88884ce15db8229b:
      title: Yarlha Shampo Sang Offering
      parent: Dharma Protectors
    407401f9aefd4dccbf574f4f59e75e48:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    2e6e256791b348849fa7302457baa70a:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    a708303705474494917e1745927e7fb5:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Rituals
    269fb72631704abe9fb8c763c4dd3cff:
      title: Sang Offering to Yellow Jambhala
      parent: Rituals
    e1f05549174449f8b4bcd085df9f31bc:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Rituals
    b7c7b91b600d414bbed4daada2e59029:
      title: 'Lasel Chenmo: A Sang Offering to the Nāgas'
      parent: Rituals
    f9f8d2393fdb4744aea03cb48c099127:
      title: Brief Sang Offering
      parent: Rituals
    9fb77a78acc1474a94b212fa72731aec:
      title: Brief Sang Offering to Purify Contamination
      parent: Rituals
    7daf5744768249c6b73eb4b2082d63ce:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Rituals
    ef14b54643d5469aa23c0452a403b625:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Riwo Sangchö
    e89273aa06a74d2e897b2a3eef0d643e:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Riwo Sangchö
    68a64455082840a285957663ea8001c8:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Riwo Sangchö
    b7f2877202a141ffbe96c339104c4437:
      title: A Concise Sang Offering to Tārā
      parent: Tārā
created_at: '2022-03-01T05:40:37.291496'
last_modified_at: '2022-03-01T05:40:37.291499'
